server:
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:shortened}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/db.changelog-root.xml
    enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: password123



host:
  name: http://localhost